// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqvoNRYGkKMDk8LB1eKIyVON6GV3Pox-o',
    appId: '1:436256385822:web:227786cbac09bd2988770f',
    messagingSenderId: '436256385822',
    projectId: 'persipal-app',
    authDomain: 'persipal-app.firebaseapp.com',
    storageBucket: 'persipal-app.firebasestorage.app',
    measurementId: 'G-39YEDE661W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr4p_M-2KX8CevKnEubECO0iyPZEDLB7s',
    appId: '1:436256385822:android:1c436ae6f6c4ba6388770f',
    messagingSenderId: '436256385822',
    projectId: 'persipal-app',
    storageBucket: 'persipal-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkC1m5xQ37kN2nYJ1_1Rth5s3LEG9lPVg',
    appId: '1:436256385822:ios:1e7a967d5c2b762c88770f',
    messagingSenderId: '436256385822',
    projectId: 'persipal-app',
    storageBucket: 'persipal-app.firebasestorage.app',
    iosBundleId: 'com.example.persipalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkC1m5xQ37kN2nYJ1_1Rth5s3LEG9lPVg',
    appId: '1:436256385822:ios:1e7a967d5c2b762c88770f',
    messagingSenderId: '436256385822',
    projectId: 'persipal-app',
    storageBucket: 'persipal-app.firebasestorage.app',
    iosBundleId: 'com.example.persipalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqvoNRYGkKMDk8LB1eKIyVON6GV3Pox-o',
    appId: '1:436256385822:web:d0ed90ceaa902c7588770f',
    messagingSenderId: '436256385822',
    projectId: 'persipal-app',
    authDomain: 'persipal-app.firebaseapp.com',
    storageBucket: 'persipal-app.firebasestorage.app',
    measurementId: 'G-JYQP2N24TY',
  );
}
